"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from livepeer_ai.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .genaudiototext import GenAudioToTextResponse, GenAudioToTextResponseTypedDict
    from .genimagetoimage import (
        GenImageToImageResponse,
        GenImageToImageResponseTypedDict,
    )
    from .genimagetotext import GenImageToTextResponse, GenImageToTextResponseTypedDict
    from .genimagetovideo import (
        GenImageToVideoResponse,
        GenImageToVideoResponseTypedDict,
    )
    from .genlivevideotovideo import (
        GenLiveVideoToVideoResponse,
        GenLiveVideoToVideoResponseTypedDict,
    )
    from .genllm import GenLLMResponse, GenLLMResponseTypedDict
    from .gensegmentanything2 import (
        GenSegmentAnything2Response,
        GenSegmentAnything2ResponseTypedDict,
    )
    from .gentexttoimage import GenTextToImageResponse, GenTextToImageResponseTypedDict
    from .gentexttospeech import (
        GenTextToSpeechResponse,
        GenTextToSpeechResponseTypedDict,
    )
    from .genupscale import GenUpscaleResponse, GenUpscaleResponseTypedDict

__all__ = [
    "GenAudioToTextResponse",
    "GenAudioToTextResponseTypedDict",
    "GenImageToImageResponse",
    "GenImageToImageResponseTypedDict",
    "GenImageToTextResponse",
    "GenImageToTextResponseTypedDict",
    "GenImageToVideoResponse",
    "GenImageToVideoResponseTypedDict",
    "GenLLMResponse",
    "GenLLMResponseTypedDict",
    "GenLiveVideoToVideoResponse",
    "GenLiveVideoToVideoResponseTypedDict",
    "GenSegmentAnything2Response",
    "GenSegmentAnything2ResponseTypedDict",
    "GenTextToImageResponse",
    "GenTextToImageResponseTypedDict",
    "GenTextToSpeechResponse",
    "GenTextToSpeechResponseTypedDict",
    "GenUpscaleResponse",
    "GenUpscaleResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "GenAudioToTextResponse": ".genaudiototext",
    "GenAudioToTextResponseTypedDict": ".genaudiototext",
    "GenImageToImageResponse": ".genimagetoimage",
    "GenImageToImageResponseTypedDict": ".genimagetoimage",
    "GenImageToTextResponse": ".genimagetotext",
    "GenImageToTextResponseTypedDict": ".genimagetotext",
    "GenImageToVideoResponse": ".genimagetovideo",
    "GenImageToVideoResponseTypedDict": ".genimagetovideo",
    "GenLiveVideoToVideoResponse": ".genlivevideotovideo",
    "GenLiveVideoToVideoResponseTypedDict": ".genlivevideotovideo",
    "GenLLMResponse": ".genllm",
    "GenLLMResponseTypedDict": ".genllm",
    "GenSegmentAnything2Response": ".gensegmentanything2",
    "GenSegmentAnything2ResponseTypedDict": ".gensegmentanything2",
    "GenTextToImageResponse": ".gentexttoimage",
    "GenTextToImageResponseTypedDict": ".gentexttoimage",
    "GenTextToSpeechResponse": ".gentexttospeech",
    "GenTextToSpeechResponseTypedDict": ".gentexttospeech",
    "GenUpscaleResponse": ".genupscale",
    "GenUpscaleResponseTypedDict": ".genupscale",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
