"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .genaudiototext import GenAudioToTextResponse, GenAudioToTextResponseTypedDict
    from .genimagetoimage import (
        GenImageToImageResponse,
        GenImageToImageResponseTypedDict,
    )
    from .genimagetotext import GenImageToTextResponse, GenImageToTextResponseTypedDict
    from .genimagetovideo import (
        GenImageToVideoResponse,
        GenImageToVideoResponseTypedDict,
    )
    from .genlivevideotovideo import (
        GenLiveVideoToVideoResponse,
        GenLiveVideoToVideoResponseTypedDict,
    )
    from .genllm import GenLLMResponse, GenLLMResponseTypedDict
    from .gensegmentanything2 import (
        GenSegmentAnything2Response,
        GenSegmentAnything2ResponseTypedDict,
    )
    from .gentexttoimage import GenTextToImageResponse, GenTextToImageResponseTypedDict
    from .gentexttospeech import (
        GenTextToSpeechResponse,
        GenTextToSpeechResponseTypedDict,
    )
    from .genupscale import GenUpscaleResponse, GenUpscaleResponseTypedDict

__all__ = [
    "GenAudioToTextResponse",
    "GenAudioToTextResponseTypedDict",
    "GenImageToImageResponse",
    "GenImageToImageResponseTypedDict",
    "GenImageToTextResponse",
    "GenImageToTextResponseTypedDict",
    "GenImageToVideoResponse",
    "GenImageToVideoResponseTypedDict",
    "GenLLMResponse",
    "GenLLMResponseTypedDict",
    "GenLiveVideoToVideoResponse",
    "GenLiveVideoToVideoResponseTypedDict",
    "GenSegmentAnything2Response",
    "GenSegmentAnything2ResponseTypedDict",
    "GenTextToImageResponse",
    "GenTextToImageResponseTypedDict",
    "GenTextToSpeechResponse",
    "GenTextToSpeechResponseTypedDict",
    "GenUpscaleResponse",
    "GenUpscaleResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "GenAudioToTextResponse": ".genaudiototext",
    "GenAudioToTextResponseTypedDict": ".genaudiototext",
    "GenImageToImageResponse": ".genimagetoimage",
    "GenImageToImageResponseTypedDict": ".genimagetoimage",
    "GenImageToTextResponse": ".genimagetotext",
    "GenImageToTextResponseTypedDict": ".genimagetotext",
    "GenImageToVideoResponse": ".genimagetovideo",
    "GenImageToVideoResponseTypedDict": ".genimagetovideo",
    "GenLiveVideoToVideoResponse": ".genlivevideotovideo",
    "GenLiveVideoToVideoResponseTypedDict": ".genlivevideotovideo",
    "GenLLMResponse": ".genllm",
    "GenLLMResponseTypedDict": ".genllm",
    "GenSegmentAnything2Response": ".gensegmentanything2",
    "GenSegmentAnything2ResponseTypedDict": ".gensegmentanything2",
    "GenTextToImageResponse": ".gentexttoimage",
    "GenTextToImageResponseTypedDict": ".gentexttoimage",
    "GenTextToSpeechResponse": ".gentexttospeech",
    "GenTextToSpeechResponseTypedDict": ".gentexttospeech",
    "GenUpscaleResponse": ".genupscale",
    "GenUpscaleResponseTypedDict": ".genupscale",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
