"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer_ai.models.components import (
    httpmetadata as components_httpmetadata,
    imagetotextresponse as components_imagetotextresponse,
)
from livepeer_ai.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GenImageToTextResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    image_to_text_response: NotRequired[
        components_imagetotextresponse.ImageToTextResponseTypedDict
    ]
    r"""Successful Response"""


class GenImageToTextResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    image_to_text_response: Optional[
        components_imagetotextresponse.ImageToTextResponse
    ] = None
    r"""Successful Response"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ImageToTextResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
