"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .apierror import APIError, APIErrorTypedDict
    from .audioresponse import AudioResponse, AudioResponseTypedDict
    from .body_genaudiototext import (
        Audio,
        AudioTypedDict,
        BodyGenAudioToText,
        BodyGenAudioToTextTypedDict,
    )
    from .body_genimagetoimage import (
        BodyGenImageToImage,
        BodyGenImageToImageTypedDict,
        Image,
        ImageTypedDict,
    )
    from .body_genimagetotext import (
        BodyGenImageToText,
        BodyGenImageToTextImage,
        BodyGenImageToTextImageTypedDict,
        BodyGenImageToTextTypedDict,
    )
    from .body_genimagetovideo import (
        BodyGenImageToVideo,
        BodyGenImageToVideoImage,
        BodyGenImageToVideoImageTypedDict,
        BodyGenImageToVideoTypedDict,
    )
    from .body_gensegmentanything2 import (
        BodyGenSegmentAnything2,
        BodyGenSegmentAnything2Image,
        BodyGenSegmentAnything2ImageTypedDict,
        BodyGenSegmentAnything2TypedDict,
    )
    from .body_genupscale import (
        BodyGenUpscale,
        BodyGenUpscaleImage,
        BodyGenUpscaleImageTypedDict,
        BodyGenUpscaleTypedDict,
    )
    from .chunk import Chunk, ChunkTypedDict
    from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
    from .imageresponse import ImageResponse, ImageResponseTypedDict
    from .imagetotextresponse import ImageToTextResponse, ImageToTextResponseTypedDict
    from .livevideotovideoparams import (
        LiveVideoToVideoParams,
        LiveVideoToVideoParamsTypedDict,
        Params,
        ParamsTypedDict,
    )
    from .livevideotovideoresponse import (
        LiveVideoToVideoResponse,
        LiveVideoToVideoResponseTypedDict,
    )
    from .llmchoice import LLMChoice, LLMChoiceTypedDict
    from .llmmessage import LLMMessage, LLMMessageTypedDict
    from .llmrequest import LLMRequest, LLMRequestTypedDict
    from .llmresponse import LLMResponse, LLMResponseTypedDict
    from .llmtokenusage import LLMTokenUsage, LLMTokenUsageTypedDict
    from .masksresponse import MasksResponse, MasksResponseTypedDict
    from .media import Media, MediaTypedDict
    from .mediaurl import MediaURL, MediaURLTypedDict
    from .security import Security, SecurityTypedDict
    from .textresponse import TextResponse, TextResponseTypedDict
    from .texttoimageparams import TextToImageParams, TextToImageParamsTypedDict
    from .texttospeechparams import TextToSpeechParams, TextToSpeechParamsTypedDict
    from .validationerror import (
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )
    from .videoresponse import VideoResponse, VideoResponseTypedDict

__all__ = [
    "APIError",
    "APIErrorTypedDict",
    "Audio",
    "AudioResponse",
    "AudioResponseTypedDict",
    "AudioTypedDict",
    "BodyGenAudioToText",
    "BodyGenAudioToTextTypedDict",
    "BodyGenImageToImage",
    "BodyGenImageToImageTypedDict",
    "BodyGenImageToText",
    "BodyGenImageToTextImage",
    "BodyGenImageToTextImageTypedDict",
    "BodyGenImageToTextTypedDict",
    "BodyGenImageToVideo",
    "BodyGenImageToVideoImage",
    "BodyGenImageToVideoImageTypedDict",
    "BodyGenImageToVideoTypedDict",
    "BodyGenSegmentAnything2",
    "BodyGenSegmentAnything2Image",
    "BodyGenSegmentAnything2ImageTypedDict",
    "BodyGenSegmentAnything2TypedDict",
    "BodyGenUpscale",
    "BodyGenUpscaleImage",
    "BodyGenUpscaleImageTypedDict",
    "BodyGenUpscaleTypedDict",
    "Chunk",
    "ChunkTypedDict",
    "HTTPMetadata",
    "HTTPMetadataTypedDict",
    "Image",
    "ImageResponse",
    "ImageResponseTypedDict",
    "ImageToTextResponse",
    "ImageToTextResponseTypedDict",
    "ImageTypedDict",
    "LLMChoice",
    "LLMChoiceTypedDict",
    "LLMMessage",
    "LLMMessageTypedDict",
    "LLMRequest",
    "LLMRequestTypedDict",
    "LLMResponse",
    "LLMResponseTypedDict",
    "LLMTokenUsage",
    "LLMTokenUsageTypedDict",
    "LiveVideoToVideoParams",
    "LiveVideoToVideoParamsTypedDict",
    "LiveVideoToVideoResponse",
    "LiveVideoToVideoResponseTypedDict",
    "Loc",
    "LocTypedDict",
    "MasksResponse",
    "MasksResponseTypedDict",
    "Media",
    "MediaTypedDict",
    "MediaURL",
    "MediaURLTypedDict",
    "Params",
    "ParamsTypedDict",
    "Security",
    "SecurityTypedDict",
    "TextResponse",
    "TextResponseTypedDict",
    "TextToImageParams",
    "TextToImageParamsTypedDict",
    "TextToSpeechParams",
    "TextToSpeechParamsTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
    "VideoResponse",
    "VideoResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "APIErrorTypedDict": ".apierror",
    "AudioResponse": ".audioresponse",
    "AudioResponseTypedDict": ".audioresponse",
    "Audio": ".body_genaudiototext",
    "AudioTypedDict": ".body_genaudiototext",
    "BodyGenAudioToText": ".body_genaudiototext",
    "BodyGenAudioToTextTypedDict": ".body_genaudiototext",
    "BodyGenImageToImage": ".body_genimagetoimage",
    "BodyGenImageToImageTypedDict": ".body_genimagetoimage",
    "Image": ".body_genimagetoimage",
    "ImageTypedDict": ".body_genimagetoimage",
    "BodyGenImageToText": ".body_genimagetotext",
    "BodyGenImageToTextImage": ".body_genimagetotext",
    "BodyGenImageToTextImageTypedDict": ".body_genimagetotext",
    "BodyGenImageToTextTypedDict": ".body_genimagetotext",
    "BodyGenImageToVideo": ".body_genimagetovideo",
    "BodyGenImageToVideoImage": ".body_genimagetovideo",
    "BodyGenImageToVideoImageTypedDict": ".body_genimagetovideo",
    "BodyGenImageToVideoTypedDict": ".body_genimagetovideo",
    "BodyGenSegmentAnything2": ".body_gensegmentanything2",
    "BodyGenSegmentAnything2Image": ".body_gensegmentanything2",
    "BodyGenSegmentAnything2ImageTypedDict": ".body_gensegmentanything2",
    "BodyGenSegmentAnything2TypedDict": ".body_gensegmentanything2",
    "BodyGenUpscale": ".body_genupscale",
    "BodyGenUpscaleImage": ".body_genupscale",
    "BodyGenUpscaleImageTypedDict": ".body_genupscale",
    "BodyGenUpscaleTypedDict": ".body_genupscale",
    "Chunk": ".chunk",
    "ChunkTypedDict": ".chunk",
    "HTTPMetadata": ".httpmetadata",
    "HTTPMetadataTypedDict": ".httpmetadata",
    "ImageResponse": ".imageresponse",
    "ImageResponseTypedDict": ".imageresponse",
    "ImageToTextResponse": ".imagetotextresponse",
    "ImageToTextResponseTypedDict": ".imagetotextresponse",
    "LiveVideoToVideoParams": ".livevideotovideoparams",
    "LiveVideoToVideoParamsTypedDict": ".livevideotovideoparams",
    "Params": ".livevideotovideoparams",
    "ParamsTypedDict": ".livevideotovideoparams",
    "LiveVideoToVideoResponse": ".livevideotovideoresponse",
    "LiveVideoToVideoResponseTypedDict": ".livevideotovideoresponse",
    "LLMChoice": ".llmchoice",
    "LLMChoiceTypedDict": ".llmchoice",
    "LLMMessage": ".llmmessage",
    "LLMMessageTypedDict": ".llmmessage",
    "LLMRequest": ".llmrequest",
    "LLMRequestTypedDict": ".llmrequest",
    "LLMResponse": ".llmresponse",
    "LLMResponseTypedDict": ".llmresponse",
    "LLMTokenUsage": ".llmtokenusage",
    "LLMTokenUsageTypedDict": ".llmtokenusage",
    "MasksResponse": ".masksresponse",
    "MasksResponseTypedDict": ".masksresponse",
    "Media": ".media",
    "MediaTypedDict": ".media",
    "MediaURL": ".mediaurl",
    "MediaURLTypedDict": ".mediaurl",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "TextResponse": ".textresponse",
    "TextResponseTypedDict": ".textresponse",
    "TextToImageParams": ".texttoimageparams",
    "TextToImageParamsTypedDict": ".texttoimageparams",
    "TextToSpeechParams": ".texttospeechparams",
    "TextToSpeechParamsTypedDict": ".texttospeechparams",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
    "VideoResponse": ".videoresponse",
    "VideoResponseTypedDict": ".videoresponse",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
