"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from livepeer_ai.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .apierror import APIError, APIErrorTypedDict
    from .audioresponse import AudioResponse, AudioResponseTypedDict
    from .body_genaudiototext import (
        Audio,
        AudioTypedDict,
        BodyGenAudioToText,
        BodyGenAudioToTextTypedDict,
    )
    from .body_genimagetoimage import (
        BodyGenImageToImage,
        BodyGenImageToImageTypedDict,
        Image,
        ImageTypedDict,
    )
    from .body_genimagetotext import (
        BodyGenImageToText,
        BodyGenImageToTextImage,
        BodyGenImageToTextImageTypedDict,
        BodyGenImageToTextTypedDict,
    )
    from .body_genimagetovideo import (
        BodyGenImageToVideo,
        BodyGenImageToVideoImage,
        BodyGenImageToVideoImageTypedDict,
        BodyGenImageToVideoTypedDict,
    )
    from .body_gensegmentanything2 import (
        BodyGenSegmentAnything2,
        BodyGenSegmentAnything2Image,
        BodyGenSegmentAnything2ImageTypedDict,
        BodyGenSegmentAnything2TypedDict,
    )
    from .body_genupscale import (
        BodyGenUpscale,
        BodyGenUpscaleImage,
        BodyGenUpscaleImageTypedDict,
        BodyGenUpscaleTypedDict,
    )
    from .chunk import Chunk, ChunkTypedDict
    from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
    from .imageresponse import ImageResponse, ImageResponseTypedDict
    from .imagetotextresponse import ImageToTextResponse, ImageToTextResponseTypedDict
    from .livevideotovideoparams import (
        LiveVideoToVideoParams,
        LiveVideoToVideoParamsTypedDict,
    )
    from .livevideotovideoresponse import (
        LiveVideoToVideoResponse,
        LiveVideoToVideoResponseTypedDict,
    )
    from .llmchoice import LLMChoice, LLMChoiceTypedDict
    from .llmmessage import LLMMessage, LLMMessageTypedDict
    from .llmrequest import LLMRequest, LLMRequestTypedDict
    from .llmresponse import LLMResponse, LLMResponseTypedDict
    from .llmtokenusage import LLMTokenUsage, LLMTokenUsageTypedDict
    from .masksresponse import MasksResponse, MasksResponseTypedDict
    from .media import Media, MediaTypedDict
    from .mediaurl import MediaURL, MediaURLTypedDict
    from .security import Security, SecurityTypedDict
    from .textresponse import TextResponse, TextResponseTypedDict
    from .texttoimageparams import TextToImageParams, TextToImageParamsTypedDict
    from .texttospeechparams import TextToSpeechParams, TextToSpeechParamsTypedDict
    from .validationerror import (
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )
    from .videoresponse import VideoResponse, VideoResponseTypedDict

__all__ = [
    "APIError",
    "APIErrorTypedDict",
    "Audio",
    "AudioResponse",
    "AudioResponseTypedDict",
    "AudioTypedDict",
    "BodyGenAudioToText",
    "BodyGenAudioToTextTypedDict",
    "BodyGenImageToImage",
    "BodyGenImageToImageTypedDict",
    "BodyGenImageToText",
    "BodyGenImageToTextImage",
    "BodyGenImageToTextImageTypedDict",
    "BodyGenImageToTextTypedDict",
    "BodyGenImageToVideo",
    "BodyGenImageToVideoImage",
    "BodyGenImageToVideoImageTypedDict",
    "BodyGenImageToVideoTypedDict",
    "BodyGenSegmentAnything2",
    "BodyGenSegmentAnything2Image",
    "BodyGenSegmentAnything2ImageTypedDict",
    "BodyGenSegmentAnything2TypedDict",
    "BodyGenUpscale",
    "BodyGenUpscaleImage",
    "BodyGenUpscaleImageTypedDict",
    "BodyGenUpscaleTypedDict",
    "Chunk",
    "ChunkTypedDict",
    "HTTPMetadata",
    "HTTPMetadataTypedDict",
    "Image",
    "ImageResponse",
    "ImageResponseTypedDict",
    "ImageToTextResponse",
    "ImageToTextResponseTypedDict",
    "ImageTypedDict",
    "LLMChoice",
    "LLMChoiceTypedDict",
    "LLMMessage",
    "LLMMessageTypedDict",
    "LLMRequest",
    "LLMRequestTypedDict",
    "LLMResponse",
    "LLMResponseTypedDict",
    "LLMTokenUsage",
    "LLMTokenUsageTypedDict",
    "LiveVideoToVideoParams",
    "LiveVideoToVideoParamsTypedDict",
    "LiveVideoToVideoResponse",
    "LiveVideoToVideoResponseTypedDict",
    "Loc",
    "LocTypedDict",
    "MasksResponse",
    "MasksResponseTypedDict",
    "Media",
    "MediaTypedDict",
    "MediaURL",
    "MediaURLTypedDict",
    "Security",
    "SecurityTypedDict",
    "TextResponse",
    "TextResponseTypedDict",
    "TextToImageParams",
    "TextToImageParamsTypedDict",
    "TextToSpeechParams",
    "TextToSpeechParamsTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
    "VideoResponse",
    "VideoResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "APIError": ".apierror",
    "APIErrorTypedDict": ".apierror",
    "AudioResponse": ".audioresponse",
    "AudioResponseTypedDict": ".audioresponse",
    "Audio": ".body_genaudiototext",
    "AudioTypedDict": ".body_genaudiototext",
    "BodyGenAudioToText": ".body_genaudiototext",
    "BodyGenAudioToTextTypedDict": ".body_genaudiototext",
    "BodyGenImageToImage": ".body_genimagetoimage",
    "BodyGenImageToImageTypedDict": ".body_genimagetoimage",
    "Image": ".body_genimagetoimage",
    "ImageTypedDict": ".body_genimagetoimage",
    "BodyGenImageToText": ".body_genimagetotext",
    "BodyGenImageToTextImage": ".body_genimagetotext",
    "BodyGenImageToTextImageTypedDict": ".body_genimagetotext",
    "BodyGenImageToTextTypedDict": ".body_genimagetotext",
    "BodyGenImageToVideo": ".body_genimagetovideo",
    "BodyGenImageToVideoImage": ".body_genimagetovideo",
    "BodyGenImageToVideoImageTypedDict": ".body_genimagetovideo",
    "BodyGenImageToVideoTypedDict": ".body_genimagetovideo",
    "BodyGenSegmentAnything2": ".body_gensegmentanything2",
    "BodyGenSegmentAnything2Image": ".body_gensegmentanything2",
    "BodyGenSegmentAnything2ImageTypedDict": ".body_gensegmentanything2",
    "BodyGenSegmentAnything2TypedDict": ".body_gensegmentanything2",
    "BodyGenUpscale": ".body_genupscale",
    "BodyGenUpscaleImage": ".body_genupscale",
    "BodyGenUpscaleImageTypedDict": ".body_genupscale",
    "BodyGenUpscaleTypedDict": ".body_genupscale",
    "Chunk": ".chunk",
    "ChunkTypedDict": ".chunk",
    "HTTPMetadata": ".httpmetadata",
    "HTTPMetadataTypedDict": ".httpmetadata",
    "ImageResponse": ".imageresponse",
    "ImageResponseTypedDict": ".imageresponse",
    "ImageToTextResponse": ".imagetotextresponse",
    "ImageToTextResponseTypedDict": ".imagetotextresponse",
    "LiveVideoToVideoParams": ".livevideotovideoparams",
    "LiveVideoToVideoParamsTypedDict": ".livevideotovideoparams",
    "LiveVideoToVideoResponse": ".livevideotovideoresponse",
    "LiveVideoToVideoResponseTypedDict": ".livevideotovideoresponse",
    "LLMChoice": ".llmchoice",
    "LLMChoiceTypedDict": ".llmchoice",
    "LLMMessage": ".llmmessage",
    "LLMMessageTypedDict": ".llmmessage",
    "LLMRequest": ".llmrequest",
    "LLMRequestTypedDict": ".llmrequest",
    "LLMResponse": ".llmresponse",
    "LLMResponseTypedDict": ".llmresponse",
    "LLMTokenUsage": ".llmtokenusage",
    "LLMTokenUsageTypedDict": ".llmtokenusage",
    "MasksResponse": ".masksresponse",
    "MasksResponseTypedDict": ".masksresponse",
    "Media": ".media",
    "MediaTypedDict": ".media",
    "MediaURL": ".mediaurl",
    "MediaURLTypedDict": ".mediaurl",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "TextResponse": ".textresponse",
    "TextResponseTypedDict": ".textresponse",
    "TextToImageParams": ".texttoimageparams",
    "TextToImageParamsTypedDict": ".texttoimageparams",
    "TextToSpeechParams": ".texttospeechparams",
    "TextToSpeechParamsTypedDict": ".texttospeechparams",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
    "VideoResponse": ".videoresponse",
    "VideoResponseTypedDict": ".videoresponse",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
