"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer_ai.types import BaseModel
from typing import Any, List, TypedDict


class ChunkTypedDict(TypedDict):
    timestamp: List[Any]
    text: str
    

class Chunk(BaseModel):
    timestamp: List[Any]
    text: str
    
