"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apierror import APIError
from livepeer_ai import utils
from livepeer_ai.types import BaseModel

class HTTPErrorData(BaseModel):
    detail: APIError
    


class HTTPError(Exception):
    r"""Bad Request"""
    data: HTTPErrorData

    def __init__(self, data: HTTPErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, HTTPErrorData)

