"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .media import Media, MediaTypedDict
from livepeer_ai.types import BaseModel
from typing import List, TypedDict


class ImageResponseTypedDict(TypedDict):
    images: List[MediaTypedDict]
    

class ImageResponse(BaseModel):
    images: List[Media]
    
