"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from livepeer_ai.types import BaseModel
from typing import TypedDict


class MediaTypedDict(TypedDict):
    url: str
    seed: int
    nsfw: bool
    

class Media(BaseModel):
    url: str
    seed: int
    nsfw: bool
    
