"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chunk import Chunk, ChunkTypedDict
from livepeer_ai.types import BaseModel
from typing import List, TypedDict


class TextResponseTypedDict(TypedDict):
    text: str
    chunks: List[ChunkTypedDict]
    

class TextResponse(BaseModel):
    text: str
    chunks: List[Chunk]
    
