"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from livepeer_ai.models.components import apierror as components_apierror
from livepeer_ai.models.errors import LivepeerError
from livepeer_ai.types import BaseModel
from typing import Optional


class HTTPErrorData(BaseModel):
    detail: components_apierror.APIError
    r"""API error response model."""


@dataclass(unsafe_hash=True)
class HTTPError(LivepeerError):
    r"""HTTP error response model."""

    data: HTTPErrorData = field(hash=False)

    def __init__(
        self,
        data: HTTPErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
