"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from livepeer_ai.models.components import validationerror as components_validationerror
from livepeer_ai.models.errors import LivepeerError
from livepeer_ai.types import BaseModel
from typing import List, Optional


class HTTPValidationErrorData(BaseModel):
    detail: Optional[List[components_validationerror.ValidationError]] = None


class HTTPValidationError(LivepeerError):
    data: HTTPValidationErrorData

    def __init__(
        self,
        data: HTTPValidationErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        self.data = data
